name: ashguy
favicon: null
layout_spectrum: 0.91068
typography_spectrum: 0.9211
title: Ash Guy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#fdfdfd'
    - '#8bbbfc'
    - '#8d624b'
    - '#5218a6'
  brandStrength: 0.531624608207494
  lightness: 0.9839393647853285
  saturation: 0.029964508255943656
  rhythmicContrast: 0.9782486550975591
purpose: []
